name: Publish npm Package

on:
  push:
    branches:
      - main
    # Optionally, you can publish on tags
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Specify your Node.js version

    - name: Install dependencies
      run: npm install
      
 - name: Install esbuild
      run: npm install esbuild --save-dev

    - name: Run build
      run: npx esbuild index.js --bundle --minify --outfile=dist/bundle.js

    - name: Build package
      run: npm run build
       # Replace with your build script
    - name: Publish package
      env:
        NODE_AUTH_TOKEN: ${{ secrets.Test }}
      run: npm publish
