name: "🚀 release"

on:
    push:
        branches:
            - main
    release:
        types: [published]

jobs:
    release:
        name: 🚀 release
        runs-on: ubuntu-latest
        steps:
            - name: 📚 checkout
              uses: actions/checkout@v4
            - name: 🟢 node
              uses: actions/setup-node@v4
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org
            - name: 📦 install
              run: npm install
              working-directory: src
            - name: 🚀 publish
              run: npm publish --access public
              working-directory: my-package
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}